steps:
  - id: build-backend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - back-end/Dockerfile
      - -t
      - ${_AR_REPO}/${_BACKEND_IMAGE}:$SHORT_SHA
      - -t
      - ${_AR_REPO}/${_BACKEND_IMAGE}:latest
      - back-end

  - id: push-backend-short-sha
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_REPO}/${_BACKEND_IMAGE}:$SHORT_SHA

  - id: push-backend-latest
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_REPO}/${_BACKEND_IMAGE}:latest

  - id: deploy-backend
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_BACKEND_SERVICE}
      - --image=${_AR_REPO}/${_BACKEND_IMAGE}:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --set-env-vars=NODE_ENV=production
      - --set-env-vars=CORS_ORIGIN=${_CORS_ORIGIN}
      - --set-env-vars=GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}
      - --set-env-vars=GCP_PROJECT_ID=${_GCP_PROJECT_ID}
      - --set-env-vars=BQ_DATASET=${_BQ_DATASET}
      - --set-env-vars=BQ_TABLE=${_BQ_TABLE}
      - --set-secrets=OPENAI_API_KEY=${_OPENAI_API_KEY_SECRET}:latest,EMAIL_HOST=${_EMAIL_HOST_SECRET}:latest,EMAIL_PORT=${_EMAIL_PORT_SECRET}:latest,EMAIL_USER=${_EMAIL_USER_SECRET}:latest,EMAIL_PASS=${_EMAIL_PASS_SECRET}:latest,EMAIL_FROM=${_EMAIL_FROM_SECRET}:latest

  - id: build-frontend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - front-end/Dockerfile
      - --build-arg
      - VITE_API_BASE_URL=${_API_BASE_URL}
      - --build-arg
      - VITE_GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}
      - -t
      - ${_AR_REPO}/${_FRONTEND_IMAGE}:$SHORT_SHA
      - -t
      - ${_AR_REPO}/${_FRONTEND_IMAGE}:latest
      - front-end

  - id: push-frontend-short-sha
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_REPO}/${_FRONTEND_IMAGE}:$SHORT_SHA

  - id: push-frontend-latest
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_REPO}/${_FRONTEND_IMAGE}:latest

  - id: deploy-frontend
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_FRONTEND_SERVICE}
      - --image=${_AR_REPO}/${_FRONTEND_IMAGE}:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated

substitutions:
  _REGION: europe-southwest1
  _AR_REPO: europe-southwest1-docker.pkg.dev/consultores-dev/repo-consultores-dev
  _BACKEND_IMAGE: backend
  _FRONTEND_IMAGE: frontend
  _BACKEND_SERVICE: backend-dev
  _FRONTEND_SERVICE: frontend-dev
  _API_BASE_URL: https://backend-dev-683216209357.europe-southwest1.run.app
  _GOOGLE_CLIENT_ID: 683216209357-dgurnrj3gvd2sbpoam4kthdona499l6r.apps.googleusercontent.com
  _CORS_ORIGIN: https://frontend-dev-683216209357.europe-southwest1.run.app
  _GCS_BUCKET_NAME: audios_consultores
  _GCP_PROJECT_ID: consultores-dev
  _BQ_DATASET: consultores
  _BQ_TABLE: Consultor
  _EMAIL_FROM: Kinedrik <automatizaciones.kinedrik@gmail.com>
  _EMAIL_FROM_SECRET: EMAIL_FROM
  _OPENAI_API_KEY_SECRET: OPENAI_API_KEY
  _EMAIL_HOST_SECRET: EMAIL_HOST
  _EMAIL_PORT_SECRET: EMAIL_PORT
  _EMAIL_USER_SECRET: EMAIL_USER
  _EMAIL_PASS_SECRET: EMAIL_PASS

images:
  - ${_AR_REPO}/${_BACKEND_IMAGE}:$SHORT_SHA
  - ${_AR_REPO}/${_BACKEND_IMAGE}:latest
  - ${_AR_REPO}/${_FRONTEND_IMAGE}:$SHORT_SHA
  - ${_AR_REPO}/${_FRONTEND_IMAGE}:latest

options:
  logging: CLOUD_LOGGING_ONLY
